package entgen

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"entgo.io/ent/entc/gen"

	"nexis.run/nexa/cmd/nexa/internal/fileplan"
)

const WorkerCommand = "__ent_generate_worker"

var defaultFeats = []string{"sql/modifier", "sql/upsert", "privacy", "entql", "sql/execquery", "intercept", "schema/snapshot"}

type workerRequest struct {
	Schema       string   `json:"schema"`
	Package      string   `json:"package"`
	Bootstrap    string   `json:"bootstrap"`
	Output       string   `json:"output"`
	Overlay      string   `json:"overlay"`
	Features     []string `json:"features"`
	TemplateDirs []string `json:"templateDirs"`
}

// PlanGenerate 在独立工作进程和临时目录中运行 Ent，只返回文件变更
func (eng *EntGen) PlanGenerate(ctx context.Context) (files []fileplan.File, err error) {
	if err = ctx.Err(); err != nil {
		return
	}

	var entPath string

	entPath, err = eng.cfg.GetEntPath()
	if err != nil {
		return
	}

	request := workerRequest{Schema: filepath.Join(entPath, "schema")}

	request.Package, err = eng.cfg.ResolvePackagePath(eng.cfg.EntPath)
	if err != nil {
		return
	}

	request.Features, err = eng.features()
	if err != nil {
		return
	}

	for _, directory := range eng.cfg.EntTemplates {
		var path string

		path, err = eng.cfg.GetAbsPath(directory)
		if err != nil {
			return
		}

		request.TemplateDirs = append(request.TemplateDirs, path)
	}

	var scratch string

	scratch, err = os.MkdirTemp(eng.cfg.RootDir, ".nexa-ent-")
	if err != nil {
		return
	}

	defer func() {
		err = errors.Join(err, os.RemoveAll(scratch))
	}()

	request.Bootstrap = filepath.Join(scratch, "bootstrap")
	request.Output = filepath.Join(scratch, "output")
	request.Overlay = filepath.Join(scratch, "overlay.json")
	var owned map[string][]byte

	owned, err = prepareBootstrap(ctx, entPath, request)
	if err != nil {
		return
	}

	err = invokeWorker(ctx, scratch, request)
	if err != nil {
		return
	}

	files, err = generatedFiles(ctx, entPath, request.Output, owned)
	if err != nil {
		return
	}

	var directives []fileplan.File

	directives, err = eng.planGenerateFile(entPath)
	if err == nil {
		files = append(files, directives...)
	}

	return
}

func (eng *EntGen) features() (features []string, err error) {
	available := make(map[string]bool)

	for _, feature := range gen.AllFeatures {
		available[feature.Name] = true
	}

	seen := make(map[string]bool)

	for _, name := range append(slices.Clone(defaultFeats), eng.cfg.EntFeatures...) {
		if !available[name] {
			err = fmt.Errorf("未知的 Ent 特性：%s", name)
			return
		}

		if !seen[name] {
			seen[name] = true
			features = append(features, name)
		}
	}
	slices.Sort(features)

	return
}

func generatedByEnt(content []byte) bool {
	return bytes.HasPrefix(content, []byte("// Code generated by ent, DO NOT EDIT.")) ||
		bytes.HasPrefix(content, []byte("// Code generated by nexa ent, DO NOT EDIT."))
}

func prepareBootstrap(ctx context.Context, entPath string, request workerRequest) (owned map[string][]byte, err error) {
	owned = make(map[string][]byte)
	replacements := make(map[string]string)

	err = os.MkdirAll(request.Bootstrap, 0755)
	if err != nil {
		return
	}

	err = filepath.WalkDir(entPath, func(path string, entry fs.DirEntry, walkErr error) (err error) {
		if walkErr != nil {
			return walkErr
		}

		if err = ctx.Err(); err != nil {
			return
		}

		if entry.IsDir() {
			if path != entPath {
				_, err = os.Stat(filepath.Join(path, "go.mod"))
				if err == nil {
					err = fmt.Errorf("输出目录包含嵌套 Go 模块：%s", path)
					return
				}

				if !os.IsNotExist(err) {
					return
				}

				err = nil
			}

			if path != entPath && (entry.Name() == "schema" || strings.HasPrefix(entry.Name(), ".")) {
				return filepath.SkipDir
			}

			return
		}

		if !entry.Type().IsRegular() || filepath.Ext(path) != ".go" || entry.Name() == "generate.go" {
			return
		}

		var content []byte

		content, err = os.ReadFile(path)
		if err != nil || !generatedByEnt(content) {
			return
		}

		var relative string

		relative, err = filepath.Rel(entPath, path)
		if err != nil {
			return
		}

		destination := filepath.Join(request.Bootstrap, relative)

		err = writeTemporary(destination, content)
		if err == nil {
			owned[relative] = content
			replacements[path] = destination
		}

		return
	})
	if err != nil {
		return
	}

	var overlay []byte

	overlay, err = json.Marshal(struct {
		Replace map[string]string
	}{Replace: replacements})
	if err == nil {
		err = os.WriteFile(request.Overlay, overlay, 0600)
	}

	return
}

func invokeWorker(ctx context.Context, directory string, request workerRequest) (err error) {
	var executable string

	executable, err = os.Executable()
	if err != nil {
		return
	}

	var input []byte

	input, err = json.Marshal(request)
	if err != nil {
		return
	}

	command := exec.CommandContext(ctx, executable, WorkerCommand)
	command.Dir = directory
	command.Stdin = bytes.NewReader(input)
	command.WaitDelay = 2 * time.Second
	configureWorkerCancellation(command)
	var output []byte

	output, err = command.CombinedOutput()
	if ctx.Err() != nil {
		err = ctx.Err()
	} else if err != nil {
		err = fmt.Errorf("生成 Ent 代码失败：%w\n%s", err, bytes.TrimSpace(output))
	}

	return
}

func generatedFiles(ctx context.Context, entPath string, output string, owned map[string][]byte) (files []fileplan.File, err error) {
	seen := make(map[string]bool)

	err = filepath.WalkDir(output, func(path string, entry fs.DirEntry, walkErr error) (err error) {
		if walkErr != nil {
			return walkErr
		}

		if err = ctx.Err(); err != nil || entry.IsDir() {
			return
		}

		if !entry.Type().IsRegular() {
			return fmt.Errorf("生成 Ent 输出不是普通文件：%s", path)
		}

		var relative string
		var content, current []byte

		relative, err = filepath.Rel(output, path)
		if err != nil {
			return
		}

		content, err = os.ReadFile(path)
		if err != nil {
			return
		}

		if filepath.Ext(path) == ".go" && !generatedByEnt(content) {
			content = append([]byte("// Code generated by nexa ent, DO NOT EDIT.\n\n"), content...)
		}

		target := filepath.Join(entPath, relative)

		current, err = os.ReadFile(target)
		if original, existed := owned[relative]; existed && (err != nil || !bytes.Equal(current, original)) {
			err = fmt.Errorf("生成期间文件已变更，未覆盖：%s", target)
			return
		}

		if err == nil && !generatedByEnt(current) {
			return fmt.Errorf("生成 Ent 输出与手写文件冲突，未覆盖：%s", target)
		}

		if err != nil && !os.IsNotExist(err) {
			return
		}

		err = nil

		files = append(files, fileplan.File{Path: target, Content: content, Overwrite: true})
		seen[relative] = true

		return
	})
	if err != nil {
		return
	}

	for relative, original := range owned {
		if !seen[relative] {
			var current []byte

			current, err = os.ReadFile(filepath.Join(entPath, relative))
			if err != nil || !bytes.Equal(current, original) {
				err = fmt.Errorf("生成期间文件已变更，未删除：%s", filepath.Join(entPath, relative))
				return
			}

			files = append(files, fileplan.File{Path: filepath.Join(entPath, relative), Overwrite: true, Remove: true})
		}
	}

	slices.SortFunc(files, func(left, right fileplan.File) int {
		return strings.Compare(left.Path, right.Path)
	})

	return
}

func writeTemporary(path string, content []byte) (err error) {
	err = os.MkdirAll(filepath.Dir(path), 0755)
	if err != nil {
		return
	}

	err = os.WriteFile(path, content, 0644)

	return
}
